version: '3.8'

services:
  # Open WebUI - A web interface for interacting with LLMs
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "3000:8080"
    volumes:
      - open-webui:/app/backend/data
    environment:
      - OLLAMA_API_BASE_URL=http://ollama:11434
    depends_on:
      - ollama
    restart: unless-stopped
    networks:
      - ollama-net

  # Ollama - Local LLM server
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ollama:/root/.ollama
    restart: unless-stopped
    networks:
      - ollama-net
    # Uncomment the following lines to automatically download models on startup
    # environment:
    #   - OLLAMA_ORIGINS=*  # Allow all origins (for development only)
    # command: >
    #   sh -c "ollama pull mistral && /bin/ollama serve"

networks:
  ollama-net:
    driver: bridge

volumes:
  open-webui:
  ollama:
